{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3/1.5.0-alpha21/material3-1.5.0-alpha21.module",
    "group": "androidx.compose.material3",
    "module": "material3",
    "version": "1.5.0-alpha21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0",
      "buildId:": "15509413"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.5.0-alpha21"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.5.0-alpha21"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha21"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3.aar",
          "url": "material3-android-1.5.0-alpha21.aar",
          "size": 4709708,
          "sha512": "31db92d41de9e29ab48e14ee01dc2bb3a33b42ca3e076a0a2036e3ce025abc32cbd2118e1df946dce0976e5e2cda25d1ee670339465a0656d3662ebec9653c1f",
          "sha256": "9bd866a84aac7f292ae09c43e24d00d745431c666537440bcc379c57ccae64be",
          "sha1": "b96b6773876daaf6704cd57bc7d36054d9e3eae0",
          "md5": "e84a1a2cebd00ae5708c5f7a77707d9e"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.5.0-alpha21"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.5.0-alpha21"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha21"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3.aar",
          "url": "material3-android-1.5.0-alpha21.aar",
          "size": 4709708,
          "sha512": "31db92d41de9e29ab48e14ee01dc2bb3a33b42ca3e076a0a2036e3ce025abc32cbd2118e1df946dce0976e5e2cda25d1ee670339465a0656d3662ebec9653c1f",
          "sha256": "9bd866a84aac7f292ae09c43e24d00d745431c666537440bcc379c57ccae64be",
          "sha1": "b96b6773876daaf6704cd57bc7d36054d9e3eae0",
          "md5": "e84a1a2cebd00ae5708c5f7a77707d9e"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.5.0-alpha21"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.5.0-alpha21"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha21"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-android-1.5.0-alpha21-sources.jar",
          "url": "material3-android-1.5.0-alpha21-sources.jar",
          "size": 900495,
          "sha512": "3d8d3c00a80ec18d32d49a51724d57b6add36472ab9cf7df88a00c96bc11030c9d54b180e737c3cebee4754e03c7ac999e78175d1343c96bcbcf9a06a9a67572",
          "sha256": "7449c11284161c4759c57757f31cd328cf7acfede47cf412e10e956066362c94",
          "sha1": "6ace645068e9b9753d4f59260bd71733fe634e0a",
          "md5": "d24620ee1cc14e59c04bdd44cec85b01"
        },
        {
          "name": "material3-1.5.0-alpha21-samples-sources.jar",
          "url": "material3-android-1.5.0-alpha21-samples-sources.jar",
          "size": 106594,
          "sha512": "c79fb0cdfd3cb7608aa11bd7b1e77ec4a71f923a5702a0936340d13ede206f2a0cf812f5cdca2e22054ec36edda6cff7314c5f3daa0d8907421bbf7f248b6a7c",
          "sha256": "c4642ca3b3172416be43f4b6e3312a49cbc6ac4d5bfaed881fa4f5d6ebf4d7b1",
          "sha1": "223194d4f313960ff4e758873d707bf531d8c23e",
          "md5": "3d357fd3cb19cbbd359ce25eac1cd3e4"
        }
      ]
    }
  ]
}